<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Repositories\AdPurchaseRepositories\**" />
    <Compile Remove="Repositories\AdPurchaseSlotRepositories\**" />
    <EmbeddedResource Remove="Repositories\AdPurchaseRepositories\**" />
    <EmbeddedResource Remove="Repositories\AdPurchaseSlotRepositories\**" />
    <None Remove="Repositories\AdPurchaseRepositories\**" />
    <None Remove="Repositories\AdPurchaseSlotRepositories\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Eigakan.Application\Eigakan.Application.csproj" />
    <ProjectReference Include="..\Eigakan.Domain\Eigakan.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.2" />
  </ItemGroup>

</Project>
